### ISSUE TITLE
Match panel p values FutureWarning and nans

### ISSUE THREAD

**Issue by alex-wenzel** [KwatME/ccal#17]
CCAL: pip version 1.0.0 (but it prints 0.9.4 on import)
Python: 3.6

Call to `make_match_panel()`:

![image](https://user-images.githubusercontent.com/32204469/56462204-29ca7100-6374-11e9-9d5e-9941658d455e.png)

results in this warning appearing twice:

![image](https://user-images.githubusercontent.com/32204469/56462212-44044f00-6374-11e9-9565-ee131d7b7451.png)

and the following match panel with `nan` for some of the *p* values:

![image](https://user-images.githubusercontent.com/32204469/56462237-95acd980-6374-11e9-8b76-c24e4b1c2f99.png)

I haven't been able to reproduce this with any other randomly-generated or real data. Here is the data that caused this error:

`PRELIM_SSGSEA`: https://drive.google.com/file/d/16uwu-cdcTF9k9Y89VPg0vVGeRiyJ2pb4/view?usp=sharing

`RPPA`: https://drive.google.com/file/d/1Jiwm1iHJvTcypGv_SvtpbNI08tIpIDtg/view?usp=sharing

**Comment by KwatME** [comment]
Thanks for the report. This has been resolved in the 1.1.0<= versions, which should be ready very soon.
